---
repos:
  - hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-json
      - id: check-added-large-files
        args: ["--maxkb=20000"]
      - id: check-yaml
      - id: debug-statements
      - id: name-tests-test
      - id: requirements-txt-fixer
      #      -
      #        id: flake8
      #        args: ['--max-line-length=100', '--ignore=E402']
      - id: check-ast
      - id: check-byte-order-marker
      - id: check-builtin-literals
      - id: check-case-conflict
      #      -
      #        id: pretty-format-json
      - id: check-symlinks
      - id: check-vcs-permalinks
      - id: check-xml
      - id: detect-private-key
      - id: double-quote-string-fixer
      - id: file-contents-sorter
      - id: fix-encoding-pragma
      - id: forbid-new-submodules
      - id: mixed-line-ending
        args: ["--fix=auto"]
      - id: no-commit-to-branch
      # pyflakes is deprecated by flake8
      #      -
      #        id: pyflakes
      - id: sort-simple-yaml
    repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: v3.1.0
  - hooks:
      - id: validate_manifest
    repo: "https://github.com/pre-commit/pre-commit"
    rev: v2.5.1
  - hooks:
      - id: reorder-python-imports
        language_version: python3.8
    repo: "https://github.com/asottile/reorder_python_imports"
    rev: v2.3.0
  - hooks:
      - id: pyupgrade
    repo: "https://github.com/asottile/pyupgrade"
    rev: v2.6.1
  - hooks:
      - id: add-trailing-comma
    repo: "https://github.com/asottile/add-trailing-comma"
    rev: v2.0.1
  - hooks:
      - id: trailing-whitespace
    repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: v3.1.0
  - hooks:
      - id: yamllint
        args:
          [
            "-d {extends: relaxed, rules: {new-lines: disable, trailing-spaces: disable, empty-lines: disable, line-length: {level: warning,max: 200}}}",
          ]
    repo: "https://github.com/adrienverge/yamllint"
    rev: v1.23.0
  - hooks:
      - id: autopep8
    repo: "https://github.com/pre-commit/mirrors-autopep8"
    rev: v1.5.3
  - hooks:
      - id: prettier
        additional_dependencies:
          - "prettier@1.1.0"
    repo: https://github.com/prettier/prettier
    rev: 2.0.5
#  -
#    hooks:
#      -
#        id: ruby-lint
#    repo: "https://github.com/pre-commit/mirrors-ruby-lint"
#    rev: v2.3.1-1
